# Generated by Django 3.1.3 on 2020-11-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegLoanerApi', '0002_auto_20201121_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expectedPaidAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='monthsPaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='realPaidAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loanAmount',
            field=models.IntegerField(default=0),
        ),
    ]
