# Generated by Django 3.1.3 on 2020-11-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegLoanerApi', '0004_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pegLoanerApi.agent'),
        ),
    ]
